# Generated by Django 5.2.1 on 2025-05-31 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_smtpsetting_delete_smtpsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smtpsetting',
            name='smtp_host',
        ),
        migrations.RemoveField(
            model_name='smtpsetting',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='smtpsetting',
            name='smtp_username',
        ),
        migrations.RemoveField(
            model_name='smtpsetting',
            name='use_tls',
        ),
        migrations.AddField(
            model_name='smtpsetting',
            name='email_host_password',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smtpsetting',
            name='email_host_user',
            field=models.EmailField(default='example.gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smtpsetting',
            name='smtp_server',
            field=models.CharField(default='smtp.gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='sendmail',
        ),
    ]
